### ISSUE TITLE
몽고DB 접속 정보 환경변수 등록

### ISSUE THREAD

**Issue by JoonSukCho** [HaeSim/gomawa_front#43]
현재 몽고DB 접속 정보가 \lib\mongodb.ts 에 하드코딩 되있습니다.
.env와 vercel 환경변수로 관리할 수 있도록 수정이 필요합니다.

**Comment by HaeSim** [comment]
![image](https://user-images.githubusercontent.com/23281453/204088432-7df10697-02a1-4f9c-ac0f-aef36bd5d25d.png)
등록완료
